/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddUser: typeof import('./src/components/Dialog/AddUser.vue')['default']
    AssignWorker: typeof import('./src/components/Dialog/AssignWorker.vue')['default']
    AuditLog: typeof import('./src/components/MainContent/AuditLog.vue')['default']
    ConfirmList: typeof import('./src/components/MainContent/ConfirmList.vue')['default']
    DataList: typeof import('./src/components/MainContent/Data-list.vue')['default']
    Distribution: typeof import('./src/components/MainContent/Distribution.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLoadingSpinner: typeof import('element-plus/es')['ElLoadingSpinner']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpinner: typeof import('element-plus/es')['ElSpinner']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    GridConfig: typeof import('./src/components/MainContent/GridConfig.vue')['default']
    Leftnav: typeof import('./src/components/Leftnav.vue')['default']
    OtherStat: typeof import('./src/components/MainContent/OtherStat.vue')['default']
    ProviceStat: typeof import('./src/components/MainContent/ProviceStat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
    Trend: typeof import('./src/components/MainContent/Trend.vue')['default']
    UserManage: typeof import('./src/components/MainContent/UserManage.vue')['default']
  }
}
